### ISSUE TITLE
CoreExampleApplication 代码运行错误

### ISSUE THREAD

**Issue by jabezGit** [dibo-software/diboot-v2-example#3]
错误日志

       __   _    __                         __
  ____/ /  (_)  / /_     ____     ____     / /_
 / __  /  / /  / __ \   / __ \   / __ \   / __/
/ /_/ /  / /  / /_/ /  / /_/ /  / /_/ /  / /_
\__,_/  /_/  /_.___/   \____/   \____/   \__/

2020-05-09 10:38:05.256  INFO 76595 --- [           main] c.e.CoreExampleApplication               : Starting CoreExampleApplication on jin-macdeMacBook-Pro.local with PID 76595 (/Users/jin-mac/X/01MEMO/diboot-v2-example/diboot-core-example/target/classes started by jin-mac in /Users/jin-mac/X/01MEMO/diboot-v2-example)
2020-05-09 10:38:05.266  INFO 76595 --- [           main] c.e.CoreExampleApplication               : No active profile set, falling back to default profiles: default
2020-05-09 10:38:06.451  WARN 76595 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
2020-05-09 10:38:06.460  INFO 76595 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-05-09 10:38:06.461 ERROR 76595 --- [           main] o.s.b.SpringApplication                  : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at com.example.CoreExampleApplication.main(CoreExampleApplication.java:32) [classes/:?]
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:203) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	... 8 more

Process finished with exit code 1

**Comment by zhichengma** [comment]
Tomcat依赖冲突问题导致，已解决
